const defaultSkills=[
{category:'Quantum Computing & Physics',skills:[['Qiskit Framework','Currently Learning','IBM Quantum,Python,Circuits'],['Quantum Gates & Circuits','Currently Learning','Pauli Gates,Hadamard,Entanglement'],['Linear Algebra for Quantum','Foundational','State Vectors,Matrices,Complex Numbers']]},
{category:'Computer Science & Programming',skills:[['Python Programming','Currently Learning','Scripting,Data Structures,Algorithms'],['C++ Basics','Interested In','Object-Oriented,Memory Management'],['Data Structures & Algorithms','Currently Learning','Arrays,Trees,Searching']]},
{category:'Mathematics & Information Theory',skills:[['Quantum Information Basics','Currently Learning','Qubits,Superposition,Measurement'],['Discrete Mathematics','Foundational','Logic,Probability,Sets']]},
{category:'Tools & Platforms',skills:[['Git & GitHub','Currently Learning','Version Control,Repositories'],['Jupyter Notebooks','Currently Learning','Python,Data Visualization']]}];
let skills=load('shahul_skills',null)||defaultSkills.map(c=>({...c,skills:c.skills.map((s,i)=>({id:c.category+i,name:s[0],level:s[1],tags:s[2].split(',')}))}));
let projects=load('shahul_projects',null)||[{id:'proj-1',title:'Single-Qubit Gate Simulator in Python',category:'Quantum Algorithms',tags:['Python','Qiskit','Linear Algebra'],summary:'A beginner project simulating Pauli-X, Hadamard, and Phase gates on state vectors using matrix multiplication.',problem:'Understanding matrix operations behind quantum logic gates can be abstract without hands-on numerical visualization.',solution:'Built a simple Python script applying 2×2 complex unitary matrices to a |0⟩ qubit state, outputting state probabilities.',repoUrl:'https://github.com'}];
let activeCategory=skills[0].category,activeFilter='All',modalType='project',alpha=1,beta=0,history=[];
function load(k,f){try{return JSON.parse(localStorage.getItem(k))||f}catch{return f}}
function save(){localStorage.setItem('shahul_skills',JSON.stringify(skills));localStorage.setItem('shahul_projects',JSON.stringify(projects))}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderSkills(){document.getElementById('skillTabs').innerHTML=skills.map(c=>`<button class="${c.category===activeCategory?'active':''}" onclick="activeCategory=${JSON.stringify(c.category)};renderSkills()">${esc(c.category)} (${c.skills.length})</button>`).join('');let cat=skills.find(c=>c.category===activeCategory);document.getElementById('skillsGrid').innerHTML=(cat?.skills||[]).map(s=>`<article class="skill"><div class="status">${esc(s.level)}</div><h3>${esc(s.name)}</h3>${s.tags.map(t=>`<span class="tag">${esc(t)}</span>`).join('')}<p><button onclick="deleteSkill('${esc(cat.category)}','${esc(s.id)}')">Remove</button></p></article>`).join('')}
function deleteSkill(c,id){skills=skills.map(x=>x.category===c?{...x,skills:x.skills.filter(s=>s.id!==id)}:x);save();renderSkills()}
function renderProjects(){let cats=['All',...new Set(projects.map(p=>p.category))];document.getElementById('projectFilters').innerHTML=cats.map(c=>`<button class="${activeFilter===c?'active':''}" onclick="activeFilter=${JSON.stringify(c)};renderProjects()">${esc(c)}</button>`).join('');let list=projects.filter(p=>activeFilter==='All'||p.category===activeFilter);document.getElementById('projectsGrid').innerHTML=list.map(p=>`<article class="project"><div><span class="status">${esc(p.category)}</span><h3>${esc(p.title)}</h3><p>${esc(p.summary)}</p>${(p.tags||[]).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div><div class="bottom"><p><b>Objective / Problem:</b><br>${esc(p.problem||'Project exploration')}</p><p><b>My approach:</b><br>${esc(p.solution||'Building and learning through implementation')}</p><p><a class="btn" href="${esc(p.repoUrl||'https://github.com')}" target="_blank" rel="noopener">View Repository ↗</a> <button onclick="deleteProject('${esc(p.id)}')">Delete</button></p></div></article>`).join('')||'<p class="muted">No projects in this category yet.</p>'}
function deleteProject(id){projects=projects.filter(p=>p.id!==id);save();renderProjects()}
function openModal(type){document.getElementById('addModal').classList.add('open');setModalType(type)}
function closeModal(){document.getElementById('addModal').classList.remove('open')}
function setModalType(type){modalType=type;document.getElementById('projectForm').classList.toggle('hidden',type!=='project');document.getElementById('skillForm').classList.toggle('hidden',type!=='skill');document.getElementById('projectTab').classList.toggle('active',type==='project');document.getElementById('skillTab').classList.toggle('active',type==='skill')}
document.getElementById('projectForm').addEventListener('submit',e=>{e.preventDefault();projects.unshift({id:'proj-'+Date.now(),title:pTitle.value.trim(),category:pCategory.value,tags:pTags.value.split(',').map(x=>x.trim()).filter(Boolean),summary:pSummary.value||'Project focused on quantum computer science concepts.',problem:'Exploring beginner challenges in algorithmic problem solving.',solution:'Implemented a software solution using programming tools.',repoUrl:pUrl.value||'https://github.com'});save();renderProjects();e.target.reset();closeModal()});
document.getElementById('skillForm').addEventListener('submit',e=>{e.preventDefault();let c=sCategory.value;if(!skills.some(x=>x.category===c))skills.push({category:c,skills:[]});skills=skills.map(x=>x.category===c?{...x,skills:[...x.skills,{id:'s-'+Date.now(),name:sName.value.trim(),level:sLevel.value,tags:sTags.value.split(',').map(t=>t.trim()).filter(Boolean)}]}:x);activeCategory=c;save();renderSkills();e.target.reset();closeModal()});
function applyGate(g){let a=alpha,b=beta;if(g==='X'){a=beta;b=alpha}else if(g==='H'){a=(alpha+beta)/Math.sqrt(2);b=(alpha-beta)/Math.sqrt(2)}else if(g==='Z'){b=-beta}else{alpha=1;beta=0;history=[];renderQubit();return}alpha=a;beta=b;history.push(g);renderQubit()}
function renderQubit(){document.getElementById('qubitOutput').innerHTML=`CURRENT STATE: ${alpha.toFixed(3)}|0⟩ + ${beta.toFixed(3)}|1⟩<br><br>|0⟩ probability: ${(alpha*alpha*100).toFixed(1)}%<br>|1⟩ probability: ${(beta*beta*100).toFixed(1)}%`;document.getElementById('gateHistory').textContent=history.length?history.join(' → '):'None (Ground State |0⟩'}
function renderSpeed(){let n=+document.getElementById('nRange').value;document.getElementById('nLabel').textContent=n;document.getElementById('classical').textContent=(2**n).toLocaleString();document.getElementById('quantum').textContent=Math.round(Math.sqrt(2**n)).toLocaleString()}
document.getElementById('nRange').addEventListener('input',renderSpeed);
document.getElementById('contactForm').addEventListener('submit',e=>{e.preventDefault();document.getElementById('formNotice').textContent='Thanks! This demo form does not send email yet; connect it to a form service or backend to receive messages.';e.target.reset()});
document.getElementById('addModal').addEventListener('click',e=>{if(e.target.id==='addModal')closeModal()});
document.getElementById('year').textContent=new Date().getFullYear();renderSkills();renderProjects();renderQubit();renderSpeed();
